### ISSUE TITLE
self.__delta = self._fail_prob/5?

### ISSUE THREAD

**Issue by htcml** [Alanthink/banditpylib#14]
In line 33 of https://github.com/Alanthink/banditpylib/blob/master/banditpylib/learners/bestarmid/fixconf/ordinarylearner/lilucb_heur.py, it uses

self.__delta = self._fail_prob/5

Why don't you let users input delta(confidence level) directly instead of fail_prob? Does this mean if I want to get confidence level 0.1 like used in the paper, I should specify fail_prob = 0.5?

**Comment by Alanthink** [comment]
`delta` in the paper does not mean confidence level. Here I follow the description of `lilUCB heuristic`.

![image](https://user-images.githubusercontent.com/17557588/76132659-0f2bd580-5fe2-11ea-80b8-57eb92a5dd6b.png)

**Comment by htcml** [comment]
In the paper, delta = 0.1 is used. Does this mean v is set to 0.5 in the paper? The paper doesn't explain what v is. Also, setting delta = 0.1 is quite large. That means the error rate can be as large as 10%. In real application, what delta should we use?

**Comment by Alanthink** [comment]
I think in the experiment description `delta` means the confidence interval (i.e., `v`). Usually, I will choose `0.05`.
